name: weather_app
description: 'A new Flutter project.'
publish_to: 'none'

version: 2.0.0+3

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  geolocator: ^12.0.0
  http: ^1.2.1
  lottie: ^3.1.2
  geocoding: ^3.0.0
  google_fonts: ^6.2.1
  get: ^4.6.6
  get_storage: ^2.1.1
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  loading_animation_widget: ^1.2.1
  flutter_dotenv: ^5.1.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
